### ISSUE TITLE
golang install broken on v93 containerbase

### ISSUE THREAD

**Issue by sp3nx0r** [containerbase/base#2166] opened 2024-02-08 21:17 UTC
Ran into this with our onprem Renovate deployment, we bump our containerbase version in our flavor of Renovate to track the modern version. We ran into issues when `install-tool golang 1.22.0` with the below issue. Reverting to containerbase 9.30.8 (the current containerbase version in mend/renovate-ce-ee docker image. 

```
ubuntu@whitesource-renovate-887498b89-hxhrk:/usr/src/app$ install-tool golang 1.22.0                                                                                                  
tool golang v1.22.0 is already installed                                                                                                                                              
linking tool golang v1.22.0                                                                                                                                                           
No /opt/containerbase/tools/golang/1.22.0/bin defined - aborting                                                                                                                      
[18:27:34.227] DEBUG (559106): discovered distro                                                                                                                                      
    distro: {                                                                                                                                                                         
      "name": "Ubuntu",                                                                                                                                                               
      "versionCode": "focal",                                                                                                                                                         
      "versionId": "20.04"                                                                                                                                                            
    }                                                                                                                                                                                 
[18:27:34.227] DEBUG (559106): prepare commands                                                                                                                                       
[18:27:34.229] INFO (559106): Installing tool golang v1.22.0...                                                                                                                       
[18:27:34.233] DEBUG (559106): supported tools                                                                                                                                        
    tools: [                                                                                                                                                                          
      "bower",                                                                                                                                                                        
      "bun",                                                                                                                                                                          
      "bundler",                                                                                                                                                                      
      "cocoapods",                                                                                                                                                                    
      "corepack",                                                                                                                                                                     
      "dart",                                                                                                                                                                         
      "docker",                                                                                                                                                                       
      "dotnet",                                                                                                                                                                       
      "flux",                                                                                                                                                                         
      "lerna",                                                                                                                                                                        
      "node",                                                                                                                                                                         
      "npm",                                                                                                                                                                          
      "pnpm",                                                                                                                                                                         
      "renovate",                                                                                                                                                                     
      "yarn",                                                                                                                                                                         
      "yarn-slim"                                                                                                                                                                     
    ]                                                                                                                                                                                 
[18:27:34.233] DEBUG (559106): Installing legacy tool golang v1.22.0 ...                                             
[18:27:34.260] FATAL (559106): Command failed with exit code 1: /usr/local/containerbase/bin/install-tool golang 1.22.0                                                               
    err: {                                                                                                                                                                            
      "type": "Error",                                                                                                                                                                
      "message": "Command failed with exit code 1: /usr/local/containerbase/bin/install-tool golang 1.22.0",                                                                          
      "stack":                                                                                                                                                                        
          Error: Command failed with exit code 1: /usr/local/containerbase/bin/install-tool golang 1.22.0                                                                             
              at makeError (/snapshot/dist/containerbase-cli.js:42922:13)                                                                                                             
              at handlePromise (/snapshot/dist/containerbase-cli.js:43378:29)                                                                                                         
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)                                                                                           
              at async InstallLegacyToolService.execute (/snapshot/dist/containerbase-cli.js:45801:5)                                                                                 
              at async InstallToolService.execute (/snapshot/dist/containerbase-cli.js:45980:9)                                                                                       
              at async InstallToolShortCommand.execute (/snapshot/dist/containerbase-cli.js:46296:14)                                                                                 
              at async InstallToolShortCommand.validateAndExecute (/snapshot/dist/containerbase-cli.js:1344:26)                                                                       
              at async _Cli.run (/snapshot/dist/containerbase-cli.js:2457:22)                                                                                                         
              at async _Cli.runExit (/snapshot/dist/containerbase-cli.js:2465:28)                                                                                                     
              at async main (/snapshot/dist/containerbase-cli.js:46439:3)                                                                                                             
      "shortMessage": "Command failed with exit code 1: /usr/local/containerbase/bin/install-tool golang 1.22.0",                                                                     
      "command": "/usr/local/containerbase/bin/install-tool golang 1.22.0",                                                                                                           
      "escapedCommand": "\"/usr/local/containerbase/bin/install-tool\" golang 1.22.0",                                                                                                
      "exitCode": 1,                                                                                                                                                                  
      "cwd": "/usr/src/app",                                                                                                                                                          
      "failed": true,                                                                                                                                                                 
      "timedOut": false,                                                                                                                                                              
      "isCanceled": false,                                                                                                                                                            
      "killed": false                                                                                                                                                                 
    }                                                                                                                                                                                 
[18:27:34.273] INFO (559106): Installed tool golang with errors in 44ms.   
```

Not sure if this is because it's become a `legacy` tool install.

**Comment by viceice** [comment] 2024-02-09 06:43
not sure what the issue is, but renovate suggested the go v1.22 update before the binaries where released.

so can you try again and check if it was a transient error?

**Comment by viceice** [comment] 2024-02-13 13:26
Closing, as this is already fixed and was a transient error

**Closed by viceice** 2024-02-13 13:26 UTC
Labels: priority-1-critical, status:requirements, tool/golang
