### ISSUE TITLE
Setup CDN to proxy/cache all sites/artifacts

### ISSUE THREAD

**Issue by setchy** [containerbase/base#1507] opened 2023-09-25 12:04 UTC
Copied from Slack discussion

> I think we need a project to set up a CDN such as through cloudflare which proxies/caches all the the sites/artifacts which containerbase might use. Maybe with cloudflare workers we can make it “serverless”. Then we could default containerbase builds to use this cdn by default, including for apache.

> If we use https://developers.cloudflare.com/cache/advanced-configuration/cache-reserve/ then it should be a “permanent” store and be able to serve content even if the upstream goes down or rate limits

**Comment by rarkins** [comment] 2023-09-25 12:16
I've registered containerbase.dev just now and propose we aim to use cdn.containerbase.dev

**Comment by viceice** [comment] 2023-10-12 12:48
Duplicate of #972

**Closed by viceice** 2023-10-12 12:48 UTC
Labels: type:feature, priority-4-low, status:requirements
