### ISSUE TITLE
`install-tool` no longer respects `https_proxy` env vars since version `9.7.0`

### ISSUE THREAD

**Issue by armingerten** [containerbase/base#1244] opened 2023-07-27 08:13 UTC
**Expected behavior**
When downloading files during execution of `install-tool` a proxy configured via `https_proxy` env var should be used to download files.

```sh
$ install-tool helm v3.12.2
[08:00:41.124] INFO (60): Installing tool helm v3.12.2...
installing v2 tool helm v3.12.2
linking tool helm v3.12.2
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /builds/argerten/playground.tmp/KUBECONFIG
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /builds/argerten/playground.tmp/KUBECONFIG
version.BuildInfo{Version:"v3.12.2", GitCommit:"1e210a2c8cc5117d1055bfaa5d40f51bbc2e345e", GitTreeState:"clean", GoVersion:"go1.20.5"}
[08:00:42.854] INFO (60): Installed tool helm in 1.7s.
```

**Actual behavior**
`install-tool` runs into a timeout (because the execution environment does not allow direct internet access).

```sh
install-tool helm v3.12.2
[07:56:46.652] INFO (57): Installing tool helm v3.12.2...
installing v2 tool helm v3.12.2
[07:56:46.863] INFO (84): Downloading file ...
    url: "https://get.helm.sh/helm-v3.12.2-linux-amd64.tar.gz"
    output: "/tmp/e967b8b92ca5b74b3690cc7c824c082b94415b513269e0d8a513bfa0e9d76e0a/helm-v3.12.2-linux-amd64.tar.gz"
[07:58:58.048] FATAL (84): connect ETIMEDOUT 152.199.21.175:443
    err: {
      "type": "RequestError",
      "message": "connect ETIMEDOUT 152.199.21.175:443",
      "stack":
          RequestError: connect ETIMEDOUT 152.199.21.175:443
              at ClientRequest.<anonymous> (/snapshot/dist/containerbase-cli.js:37024:94)
              at Object.onceWrapper (node:events:652:26)
              at ClientRequest.emit (node:events:549:35)
              at TLSSocket.socketErrorListener (node:_http_client:465:9)
              at TLSSocket.emit (node:events:537:28)
              at emitErrorNT (node:internal/streams/destroy:151:8)
              at emitErrorCloseNT (node:internal/streams/destroy:116:3)
              at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
              at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1237:16)
      "code": "ETIMEDOUT",
      "timings": {
        "start": 1690444606872,
        "socket": 1690444606873,
        "lookup": 1690444607065,
        "error": 1690444738037,
        "phases": {
          "wait": 1,
          "dns": 192,
          "total": 131165
        }
      },
      "name": "RequestError",
      "options": {
        "agent": {},
        "decompress": true,
        "timeout": {},
        "prefixUrl": "",
        "ignoreInvalidCookies": false,
        "context": {},
        "hooks": {
          "init": [],
          "beforeRequest": [],
          "beforeError": [],
          "beforeRedirect": [],
          "beforeRetry": [],
          "afterResponse": []
        },
        "followRedirect": true,
        "maxRedirects": 10,
        "throwHttpErrors": true,
        "username": "",
        "password": "",
        "http2": false,
        "allowGetBody": false,
        "headers": {
          "user-agent": "got (https://github.com/sindresorhus/got)",
          "accept-encoding": "gzip, deflate, br"
        },
        "methodRewriting": false,
        "retry": {
          "limit": 2,
          "methods": [
            "GET",
            "PUT",
            "HEAD",
            "DELETE",
            "OPTIONS",
            "TRACE"
          ],
          "statusCodes": [
            408,
            413,
            429,
            500,
            502,
            503,
            504,
            521,
            522,
            524
          ],
          "errorCodes": [
            "ETIMEDOUT",
            "ECONNRESET",
            "EADDRINUSE",
            "ECONNREFUSED",
            "EPIPE",
            "ENOTFOUND",
            "ENETUNREACH",
            "EAI_AGAIN"
          ],
          "backoffLimit": null,
          "noise": 100
        },
        "method": "GET",
        "cacheOptions": {},
        "https": {},
        "resolveBodyOnly": false,
        "isStream": true,
        "responseType": "text",
        "url": "https://get.helm.sh/helm-v3.12.2-linux-amd64.tar.gz",
        "pagination": {
          "countLimit": null,
          "backoff": 0,
          "requestLimit": 10000,
          "stackAllItems": false
        },
        "setHost": true,
        "enableUnixSockets": false
      }
    }
[07:58:58.051] INFO (84): Download completed with errors  in 2m 11.1s.
Download failed: https://get.helm.sh/helm-v3.12.2-linux-amd64.tar.gz
[07:58:58.065] FATAL (57): Command failed with exit code 1: /usr/local/containerbase/bin/install-tool helm 3.12.2
    err: {
      "type": "Error",
      "message": "Command failed with exit code 1: /usr/local/containerbase/bin/install-tool helm 3.12.2",
      "stack":
          Error: Command failed with exit code 1: /usr/local/containerbase/bin/install-tool helm 3.12.2
              at makeError (/snapshot/dist/containerbase-cli.js:38310:13)
              at handlePromise (/snapshot/dist/containerbase-cli.js:38765:29)
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
              at async InstallLegacyToolService.execute (/snapshot/dist/containerbase-cli.js:39637:5)
              at async InstallToolService.execute (/snapshot/dist/containerbase-cli.js:39803:7)
              at async InstallToolShortCommand.execute (/snapshot/dist/containerbase-cli.js:39872:14)
              at async InstallToolShortCommand.validateAndExecute (/snapshot/dist/containerbase-cli.js:1342:26)
              at async _Cli.run (/snapshot/dist/containerbase-cli.js:2455:22)
              at async _Cli.runExit (/snapshot/dist/containerbase-cli.js:2463:28)
              at async main (/snapshot/dist/containerbase-cli.js:40006:3)
      "shortMessage": "Command failed with exit code 1: /usr/local/containerbase/bin/install-tool helm 3.12.2",
      "command": "/usr/local/containerbase/bin/install-tool helm 3.12.2",
      "escapedCommand": "\"/usr/local/containerbase/bin/install-tool\" helm 3.12.2",
      "exitCode": 1,
      "failed": true,
      "timedOut": false,
      "isCanceled": false,
      "killed": false
    }
[07:58:58.073] INFO (57): Installed tool helm with errors in 2m 11.4s.
```

This used to work until version `9.6.2` and broke with version `9.7.0`. I'd suspect the replacement of curl to download files to cause this issue: https://github.com/containerbase/base/commit/cdec808f716fa8dd8ad3c9d8302e9d0663ef85ab#diff-28a534928943da3d486bb4bdd14e9440275bca5c1ff6ba37e8e8aab6c9857f8bR93

**Comment by viceice** [comment] 2023-07-27 13:52
Duplicate of #1237

**Closed** 2023-07-27 13:52 UTC
